// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webApi;

#nullable disable

namespace webApi.Migrations
{
    [DbContext(typeof(ApplicationDB))]
    [Migration("20230307201908_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("webApi.Data.Acuario", b =>
                {
                    b.Property<int>("AcuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcuarioID"), 1L, 1);

                    b.Property<string>("Nombre_Acuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maximo_visitantes")
                        .HasColumnType("int");

                    b.Property<string>("ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AcuarioID");

                    b.ToTable("Acuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
